
import React, { useState, useEffect, useMemo } from 'react';
import type { Site, RssItem, PostHistoryItem, ApiKeys } from '../types';
import { GenerateTab } from './GenerateTab';
import { SocialGraphicsTab } from './SocialGraphicsTab';
import { SocialVideoTab } from './SocialVideoTab';
import { EmailMarketingTab } from './EmailMarketingTab';
import { DraftsTab } from './DraftsTab';
import { HistoryTab } from './HistoryTab';
import { DocumentTextIcon, PhotoIcon, VideoCameraIcon, MailIcon, PenIcon, ArchiveBoxIcon, LightbulbIcon, XIcon } from './Icons';
import { NextStepGuide } from './NextStepGuide';
import { UpgradePlan } from './UpgradePlan';

interface ContentHubTabProps {
    site: Site;
    onSiteUpdate: (field: keyof Site, value: any) => void;
    onMultipleSiteUpdates: (updates: Partial<Site>) => void;
    onGenerateAndScore: (topicToTrack: string, generationSource: 'keyword' | 'rss' | 'video' | 'google_sheet' | 'agency_agent', sourceDetails: any, site: Site) => Promise<void>;
    onReviewDraft: (draftId: string) => void;
    onDiscardDraft: (draftId: string) => void;
    onViewHistory: (item: PostHistoryItem) => void;
    setActiveTab: (tab: string, subTab?: string | null) => void;
    setError: (error: string | null) => void;
    logApiUsage: (provider: keyof ApiKeys, cost: number) => void;
    initialSubTab: string | null;
    onRefreshAnalytics: () => Promise<void>;
    onRefreshClarityData: () => Promise<void>;
    onRefreshArticle: (url: string, site: Site) => Promise<void>;
    isAgencyContext?: boolean;
    planAccess: any;
}

const planPillClasses: Record<string, string> = {
    creator: 'bg-brand-primary/10 text-brand-primary border border-brand-primary/20 shadow-sm',
    pro: 'bg-brand-primary/10 text-brand-primary border border-brand-primary/20 shadow-sm',
    agency: 'bg-brand-primary/10 text-brand-primary border border-brand-primary/20 shadow-sm',
};

const TabGuide: React.FC<{ title: string; children: React.ReactNode; }> = ({ title, children }) => {
    const [isVisible, setIsVisible] = useState(true);
    if (!isVisible) return null;
    return (
        <div className="bg-brand-primary/10 p-5 rounded-xl border border-brand-primary/30 shadow-sm mb-8 flex items-start gap-4 animate-fade-in relative overflow-hidden border-y border-r border-border-subtle">
            <div className="absolute -right-6 -top-6 opacity-[0.03] pointer-events-none">
                <LightbulbIcon className="h-32 w-32 text-brand-primary" />
            </div>
            <div className="p-2 bg-brand-primary/10 rounded-full flex-shrink-0 relative z-10">
                <LightbulbIcon className="h-5 w-5 text-brand-primary" />
            </div>
            <div className="flex-1 pt-0.5 relative z-10">
                <h3 className="font-bold text-main text-lg">{title}</h3>
                <div className="text-sm text-text-secondary mt-1 leading-relaxed">
                    {children}
                </div>
            </div>
            <button 
                onClick={() => setIsVisible(false)} 
                className="p-1.5 text-text-tertiary hover:text-main rounded-full relative z-10 transition-colors hover:bg-bg-surface-highlight"
            >
                <XIcon className="h-5 w-5" />
            </button>
        </div>
    );
};

const guideContent: Record<string, { title: string, description: React.ReactNode }> = {
    blog: {
        title: "Manage Your Content Ideas",
        description: <p>This is where you fuel your content engine. Add topics to your <strong>Keyword List</strong>, connect <strong>RSS Feeds</strong> or <strong>Video Sources</strong> for inspiration, or use the AI to suggest new ideas.</p>
    },
    graphics: {
        title: "On-Demand Social Graphics",
        description: <p>Create engaging, branded images for your social media channels. Just provide a prompt, choose an aspect ratio, and let the AI do the rest. You can even use characters you've defined in the Branding tab.</p>
    },
    video: {
        title: "AI-Powered Video Production",
        description: <p>Generate high-quality, short-form videos from a simple prompt. The AI creates a storyboard and edits scenes together for a professional result, perfect for social media.</p>
    },
    email: {
        title: "Email Marketing Campaigns",
        description: <p>Craft and send complete email newsletters using AI. Provide a topic, and the AI will generate a compelling subject line and HTML body, ready to be sent via your connected Mailchimp account.</p>
    },
    drafts: {
        title: "Review Your Drafts",
        description: <p>Posts generated by your automation workflows will appear here if you have <strong>Human Review</strong> enabled. Review, edit, and publish them when you're ready.</p>
    },
    history: {
        title: "Your Content Archive",
        description: <p>Browse all the content that has been generated and published for this site. Click 'View Details' to see social media posts and performance analytics for each item.</p>
    }
};

export const ContentHubTab: React.FC<ContentHubTabProps> = (props) => {
    const [activeSubTab, setActiveSubTab] = useState(props.initialSubTab || 'blog');
    const { isAgencyContext, planAccess } = props;

    useEffect(() => {
        if (props.initialSubTab) {
            setActiveSubTab(props.initialSubTab);
        }
    }, [props.initialSubTab]);

    useEffect(() => {
        // Scroll to top when sub-tab changes
        document.querySelector('main')?.scrollTo({ top: 0, behavior: 'smooth' });
    }, [activeSubTab]);
    
    const subTabs = [
        { id: 'blog', label: 'Blog Posts', icon: DocumentTextIcon },
        { id: 'graphics', label: 'Social Graphics', icon: PhotoIcon, plan: 'creator' as const },
        { id: 'video', label: 'Social Video', icon: VideoCameraIcon, plan: 'pro' as const },
        { id: 'email', label: 'Email Campaigns', icon: MailIcon, plan: 'pro' as const },
        { id: 'drafts', label: 'Drafts', icon: PenIcon },
        { id: 'history', label: 'History', icon: ArchiveBoxIcon },
    ];

    const hasKeywords = useMemo(() => props.site.keywordList.split('\n').some(k => k.trim() && !k.trim().startsWith('[DONE]')), [props.site.keywordList]);
    const currentGuide = guideContent[activeSubTab];
    
    const isLocked = 
        (activeSubTab === 'graphics' && !planAccess.canUseSocialGraphicsAutomation) ||
        (activeSubTab === 'video' && !planAccess.canUseSocialVideoAutomation) ||
        (activeSubTab === 'email' && !planAccess.canUseEmailMarketing);

    return (
        <div className="w-full max-w-7xl mx-auto space-y-8">
            <div className="border-b border-border">
                <nav className="-mb-px flex space-x-6 overflow-x-auto" aria-label="Tabs">
                    {subTabs.map(tab => (
                        <button
                            key={tab.id}
                            onClick={() => setActiveSubTab(tab.id)}
                            className={`${
                                activeSubTab === tab.id
                                    ? 'border-brand-primary text-brand-primary'
                                    : 'border-transparent text-sub hover:text-main hover:border-gray-500'
                            } flex items-center gap-2 whitespace-nowrap py-3 px-1 border-b-2 font-medium text-sm transition-colors`}
                            aria-current={activeSubTab === tab.id ? 'page' : undefined}
                        >
                            <tab.icon className="h-5 w-5" />
                            {tab.label}
                            {!isAgencyContext && tab.plan && (
                                <span className={`ml-2 px-2 py-0.5 rounded-full text-[10px] font-bold uppercase tracking-wider ${planPillClasses[tab.plan]}`}>
                                    {tab.plan}
                                </span>
                            )}
                        </button>
                    ))}
                </nav>
            </div>
            
            {currentGuide && !isLocked && (
                <TabGuide title={currentGuide.title}>
                    {currentGuide.description}
                </TabGuide>
            )}

            <div key={activeSubTab} className="animate-fade-in">
                {isLocked ? (
                    <UpgradePlan 
                        featureName={
                            activeSubTab === 'graphics' ? 'Social Graphics' : 
                            activeSubTab === 'video' ? 'Social Video' : 
                            activeSubTab === 'email' ? 'Email Marketing' : 'Premium Feature'
                        } 
                        requiredPlan={
                            activeSubTab === 'graphics' ? 'Creator' : 'Pro'
                        } 
                        setActiveTab={props.setActiveTab} 
                    />
                ) : (
                    <>
                        {activeSubTab === 'blog' && <GenerateTab site={props.site} onSiteUpdate={props.onSiteUpdate} onGenerateAndScore={props.onGenerateAndScore} setActiveTab={props.setActiveTab} setError={props.setError} logApiUsage={props.logApiUsage} onRefreshArticle={props.onRefreshArticle} />}
                        {activeSubTab === 'graphics' && <SocialGraphicsTab site={props.site} onSiteUpdate={props.onSiteUpdate} logApiUsage={props.logApiUsage} setError={props.setError} />}
                        {activeSubTab === 'video' && <SocialVideoTab site={props.site} onSiteUpdate={props.onSiteUpdate} logApiUsage={props.logApiUsage} setError={props.setError} />}
                        {activeSubTab === 'email' && <EmailMarketingTab site={props.site} onSiteUpdate={props.onSiteUpdate} logApiUsage={props.logApiUsage} setError={props.setError} />}
                        {activeSubTab === 'drafts' && <DraftsTab drafts={props.site.drafts || []} onReview={props.onReviewDraft} onDiscard={props.onDiscardDraft} />}
                        {activeSubTab === 'history' && <HistoryTab site={props.site} history={props.site.history || []} onViewDetails={props.onViewHistory} onRefreshAnalytics={props.onRefreshAnalytics} onRefreshClarityData={props.onRefreshClarityData} />}
                    </>
                )}
            </div>

            {hasKeywords && !props.site.isAutomationEnabled && activeSubTab === 'blog' && (
                <NextStepGuide
                    label="Set Up Automation"
                    description="You have content ideas ready to go. Head over to the Automation tab to set up a schedule and let the AI generate content for you automatically."
                    onClick={() => props.setActiveTab('automation')}
                />
            )}
        </div>
    );
};
