import React, { useState, useEffect } from 'react';
import type { Site, RssItem, PostHistoryItem, ApiKeys } from '../types';
import { GenerateTab } from './GenerateTab';
import { SocialGraphicsTab } from './SocialGraphicsTab';
import { SocialVideoTab } from './SocialVideoTab';
import { EmailMarketingTab } from './EmailMarketingTab';
import { DraftsTab } from './DraftsTab';
import { HistoryTab } from './HistoryTab';
import { DocumentTextIcon, PhotoIcon, VideoCameraIcon, MailIcon, PenIcon, ArchiveBoxIcon, LightbulbIcon, XIcon } from './Icons';

interface ContentHubTabProps {
    site: Site;
    onSiteUpdate: (field: keyof Site, value: any) => void;
    onMultipleSiteUpdates: (updates: Partial<Site>) => void;
    onGenerateAndScore: (topicToTrack: string, generationSource: 'keyword' | 'rss' | 'video' | 'google_sheet', sourceDetails: RssItem | string, site: Site) => Promise<void>;
    onReviewDraft: (draftId: string) => void;
    onDiscardDraft: (draftId: string) => void;
    onViewHistory: (item: PostHistoryItem) => void;
    setActiveTab: (tab: string, subTab?: string | null) => void;
    setError: (error: string | null) => void;
    logApiUsage: (provider: keyof ApiKeys, cost: number) => void;
    initialSubTab: string | null;
    onRefreshAnalytics: () => Promise<void>;
    onRefreshClarityData: () => Promise<void>;
    onRefreshArticle: (url: string, site: Site) => Promise<void>;
}

const TabGuide: React.FC<{ title: string; children: React.ReactNode; }> = ({ title, children }) => {
    const [isVisible, setIsVisible] = useState(true);
    if (!isVisible) return null;
    return (
        <div className="bg-blue-900/20 p-4 rounded-lg border border-blue-500/30 mb-8 flex items-start gap-4 animate-fade-in">
            <LightbulbIcon className="h-6 w-6 text-blue-300 flex-shrink-0 mt-1" />
            <div className="flex-1">
                <h3 className="font-bold text-white">{title}</h3>
                <div className="text-sm text-blue-200/80 mt-1">
                    {children}
                </div>
            </div>
            <button onClick={() => setIsVisible(false)} className="p-1.5 text-blue-200/60 hover:text-white rounded-full">
                <XIcon className="h-5 w-5" />
            </button>
        </div>
    );
};

const guideContent: Record<string, { title: string, description: React.ReactNode }> = {
    blog: {
        title: "Manage Your Content Ideas",
        description: <p>This is where you fuel your content engine. Add topics to your <strong>Keyword List</strong>, connect <strong>RSS Feeds</strong> or <strong>Video Sources</strong> for inspiration, or use the AI to suggest new ideas.</p>
    },
    graphics: {
        title: "On-Demand Social Graphics",
        description: <p>Create engaging, branded images for your social media channels. Just provide a prompt, choose an aspect ratio, and let the AI do the rest. You can even use characters you've defined in the Branding tab.</p>
    },
    video: {
        title: "AI-Powered Video Production",
        description: <p>Generate high-quality, short-form videos from a simple prompt. The AI creates a storyboard and edits scenes together for a professional result, perfect for social media.</p>
    },
    email: {
        title: "Email Marketing Campaigns",
        description: <p>Craft and send complete email newsletters using AI. Provide a topic, and the AI will generate a compelling subject line and HTML body, ready to be sent via your connected Mailchimp account.</p>
    },
    drafts: {
        title: "Review Your Drafts",
        description: <p>Posts generated by your automation workflows will appear here if you have <strong>Human Review</strong> enabled. Review, edit, and publish them when you're ready.</p>
    },
    history: {
        title: "Your Content Archive",
        description: <p>Browse all the content that has been generated and published for this site. Click 'View Details' to see social media posts and performance analytics for each item.</p>
    }
};

export const ContentHubTab: React.FC<ContentHubTabProps> = (props) => {
    const [activeSubTab, setActiveSubTab] = useState(props.initialSubTab || 'blog');

    useEffect(() => {
        if (props.initialSubTab) {
            setActiveSubTab(props.initialSubTab);
        }
    }, [props.initialSubTab]);
    
    const subTabs = [
        { id: 'blog', label: 'Blog Posts', icon: DocumentTextIcon },
        { id: 'graphics', label: 'Social Graphics', icon: PhotoIcon },
        { id: 'video', label: 'Social Video', icon: VideoCameraIcon },
        { id: 'email', label: 'Email Campaigns', icon: MailIcon },
        { id: 'drafts', label: 'Drafts', icon: PenIcon },
        { id: 'history', label: 'History', icon: ArchiveBoxIcon },
    ];

    const currentGuide = guideContent[activeSubTab];
    
    return (
        <div className="w-full max-w-5xl mx-auto">
            <div className="border-b border-border mb-8">
                <nav className="-mb-px flex space-x-6 overflow-x-auto" aria-label="Tabs">
                    {subTabs.map(tab => (
                        <button
                            key={tab.id}
                            onClick={() => setActiveSubTab(tab.id)}
                            className={`${
                                activeSubTab === tab.id
                                    ? 'border-blue-500 text-blue-400'
                                    : 'border-transparent text-text-secondary hover:text-text-primary hover:border-gray-500'
                            } flex items-center gap-2 whitespace-nowrap py-3 px-1 border-b-2 font-medium text-sm transition-colors`}
                            aria-current={activeSubTab === tab.id ? 'page' : undefined}
                        >
                            <tab.icon className="h-5 w-5" />
                            {tab.label}
                        </button>
                    ))}
                </nav>
            </div>
            
            {currentGuide && (
                <TabGuide title={currentGuide.title}>
                    {currentGuide.description}
                </TabGuide>
            )}

            <div key={activeSubTab} className="animate-fade-in">
                {activeSubTab === 'blog' && <GenerateTab site={props.site} onSiteUpdate={props.onSiteUpdate} onGenerateAndScore={props.onGenerateAndScore} setActiveTab={props.setActiveTab} setError={props.setError} logApiUsage={props.logApiUsage} onRefreshArticle={props.onRefreshArticle} />}
                {activeSubTab === 'graphics' && <SocialGraphicsTab site={props.site} onSiteUpdate={props.onSiteUpdate} logApiUsage={props.logApiUsage} setError={props.setError} />}
                {activeSubTab === 'video' && <SocialVideoTab site={props.site} onSiteUpdate={props.onSiteUpdate} logApiUsage={props.logApiUsage} setError={props.setError} />}
                {activeSubTab === 'email' && <EmailMarketingTab site={props.site} onSiteUpdate={props.onSiteUpdate} logApiUsage={props.logApiUsage} setError={props.setError} />}
                {activeSubTab === 'drafts' && <DraftsTab drafts={props.site.drafts || []} onReview={props.onReviewDraft} onDiscard={props.onDiscardDraft} />}
                {activeSubTab === 'history' && <HistoryTab site={props.site} history={props.site.history || []} onViewDetails={props.onViewHistory} onRefreshAnalytics={props.onRefreshAnalytics} onRefreshClarityData={props.onRefreshClarityData} />}
            </div>
        </div>
    );
};
